remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title:  "Tabete"
description: Tabete is an open invitation to pull up a seat at our kotatsu-style table and feast on creativity, collaboration, and transparency.
