remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
title:  "Tabete"
description: Tabete is an open invitation to pull up a seat at our table and feast on creativity, collaboration and transparency.

collections:
  pages:
    output: true
    permalink: /:name/
  authors:
    output: true          # tells Jekyll to publish the files
    permalink: /author/:name/
