remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
- jekyll-seo-tag

title:  "Tabete"
description: Tabete is a community of consultants collaborating and sharing ideas. Pull up a seat at our table!

collections:
  pages:
    output: true
    permalink: /:name/
  authors:
    output: true          # tells Jekyll to publish the files
    permalink: /author/:name/
