name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  stage-deploy:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - name: Download Jekyll site artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          gh run download -R ${{ github.repository }} -D _site -n site-${{ github.sha }} >> GITHUB_STEP_SUMMARY

      - name: verify site directory
        run: |
          set -x
          if [ ! -d "_site" ]; then
            echo "Error: \`_site\` directory does not exist. Ensure that an artifact \`site-${{ github.sha }}\` exists." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            ls -la _site
          fi

      - name: Upload Pages artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          retention-days: 1
          name: github-pages-${{ github.repository_id }}-${{ github.sha }}

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.repository_id }}-${{ github.sha }}

      - name: Set deployment status
        id: deployed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
        run: |
          gh extension install lakruzz/gh-set-status
          if [[ "${{ steps.deployment.outcome }}" == "success" && "${{ steps.deployment.outputs.page_url }}" != "" ]]; then
            echo "Deployment successful: ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
            gh set-status success "Deployment successful: ${{ steps.deployment.outputs.page_url }}"
          else
            echo "Deployment failed." >> $GITHUB_STEP_SUMMARY
            gh set-status failure "Deployment failed"
            # Don't exit 1 here to allow workflow to continue
          fi
