name: wrapup
on:
  workflow_dispatch:

  push:
    branches:
      - "[0-9]*" # Isue branches
      - "copilot/*" # Copilot running in Agentic mode pushes branches with this prefix as default

concurrency:
  group: "wrapup"
  cancel-in-progress: false

jobs:
  trunk-worthy:
    name: Check trunk worthyness
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up runner environment
        uses: ./.github/actions/prep-runner
        with:
          verify: ./.scripts/trunk-worthy
